version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "7201:8080"
        depends_on:
          - db
          - kibana

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"

    elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
      # 8.x
      environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
      ports:
        - 9200:9200
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      networks:
        - elastic

    kibana:
      image: docker.elastic.co/kibana/kibana:8.7.1
      container_name: kibana
      environment:
        - ELASTICSEARCH_URL=http://localhost:9200
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
      networks:
        - elastic

networks:
  elastic:
volumes:
  elasticsearch-data: